### ISSUE TITLE
Link to preprocessed char-CNN-RNN text embeddings for birds is down

### ISSUE THREAD

**Issue by marcomenardi** [hanzhanggit/StackGAN-v2#13]

**Comment by marcomenardi** [comment]
Now it is working

**Comment by mitsukimon** [comment]
can you share the link with me too .. I have this link here 
https://drive.google.com/open?id=0B3y_msrWZaXLT1BZdVdycDY5TEE
I tried to get access to this file for 3 days and it hasn't been approved. I am kind of losing my mind here

**Comment by kshitijagrwl** [comment]
Same issue - any update on the link ?
