### ISSUE TITLE
/data/birds/train/filenames.pickle

### ISSUE THREAD

**Issue by camhilker** [hanzhanggit/StackGAN-v2#37]
When running main.py on the birds dataset, I get an error:

`IOError: [Errno 2] No such file or directory: u'../data/birds/train/filenames.pickle'`

How is /data/birds/train/filenames.pickle generated? I downloaded the CUB_200_2011 dataset and unzipped into /data/birds/CUB_200_2011

Thank you

**Comment by mitsukimon** [comment]
it looks like you should download the pickle file too ...

**Comment by DataSenseiAryan** [comment]
where is that pickle file? I m unable to find it. Thank you.
